apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 1.6.x
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 1h
  targetNamespace: longhorn-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    service:
      ui:
        type: ClusterIP
    defaultSettings:
      defaultDataPath: /mnt/storage-data01
  postRenderers:
  - kustomize:
      patches:
      - target:
          kind: Deployment
        patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: ignored\n\
          \  annotations:\n    trivy.aquasecurity.github.io/ignore-audit-policies:\
          \ \"AVD-KSV-0001,AVD-KSV-0003,AVD-KSV-0004,AVD-KSV-0011,AVD-KSV-0012,AVD-KSV-0014,AVD-KSV-0015,AVD-KSV-0016,AVD-KSV-0017,AVD-KSV-0018,AVD-KSV-0020,AVD-KSV-0021,AVD-KSV-0023,AVD-KSV-0030,AVD-KSV-0036,AVD-KSV-0104,AVD-KSV-0105,AVD-KSV-0106,AVD-KSV-0118,AVD-KSV-0121,AVD-KSV-0125\""
      - target:
          kind: DaemonSet
        patch: "apiVersion: apps/v1\nkind: DaemonSet\nmetadata:\n  name: ignored\n\
          \  annotations:\n    trivy.aquasecurity.github.io/ignore-audit-policies:\
          \ \"AVD-KSV-0001,AVD-KSV-0003,AVD-KSV-0004,AVD-KSV-0011,AVD-KSV-0012,AVD-KSV-0014,AVD-KSV-0015,AVD-KSV-0016,AVD-KSV-0017,AVD-KSV-0018,AVD-KSV-0020,AVD-KSV-0021,AVD-KSV-0023,AVD-KSV-0030,AVD-KSV-0036,AVD-KSV-0104,AVD-KSV-0105,AVD-KSV-0106,AVD-KSV-0118,AVD-KSV-0121,AVD-KSV-0125\""
      - target:
          kind: ReplicaSet
        patch: "apiVersion: apps/v1\nkind: ReplicaSet\nmetadata:\n  name: ignored\n\
          \  annotations:\n    trivy.aquasecurity.github.io/ignore-audit-policies:\
          \ \"AVD-KSV-0001,AVD-KSV-0003,AVD-KSV-0004,AVD-KSV-0011,AVD-KSV-0012,AVD-KSV-0014,AVD-KSV-0015,AVD-KSV-0016,AVD-KSV-0017,AVD-KSV-0018,AVD-KSV-0020,AVD-KSV-0021,AVD-KSV-0023,AVD-KSV-0030,AVD-KSV-0036,AVD-KSV-0104,AVD-KSV-0105,AVD-KSV-0106,AVD-KSV-0118,AVD-KSV-0121,AVD-KSV-0125\""
