apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-controller-flux-system
  annotations:
    trivy.aquasecurity.github.io/ignore-audit-policies: "AVD-KSV-0041,AVD-KSV-0046,AVD-KSV-0049"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-edit-flux-system
  annotations:
    trivy.aquasecurity.github.io/ignore-audit-policies: "AVD-KSV-0046"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-view-flux-system
  annotations:
    trivy.aquasecurity.github.io/ignore-audit-policies: "AVD-KSV-0046"
