apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-delegator
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: vault-auth-delegator
type: kubernetes.io/service-account-token
