apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://192.168.0.40:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-ca-cert
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "k3s-stage-monitoring"
          serviceAccountRef:
            name: grafana-vault-auth
