apiVersion: v1
kind: Secret
metadata:
  name: vault-ca-cert
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFjTCCA3WgAwIBAgIUXuOL5UW/xkMx4uosHxRM99/MXfUwDQYJKoZIhvcNAQEL
    BQAwVjELMAkGA1UEBhMCVVMxEjAQBgNVBAoMCUpORVQtTGFiczEWMBQGA1UECwwN
    VmF1bHQtQ29udHJvbDEbMBkGA1UEAwwSSk5FVC1WYXVsdC1Sb290LUNBMB4XDTI2
    MDgyODAxNTUyNFoXDTM2MDgyNTAxNTUyNFowVjELMAkGA1UEBhMCVVMxEjAQBgNV
    BAoMCUpORVQtTGFiczEWMBQGA1UECwwNVmF1bHQtQ29udHJvbDEbMBkGA1UEAwwS
    Sk5FVC1WYXVsdC1Sb290LUNBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
    AgEAnHIo8ymySuJG4yXlkT/dg14s+9tVcz0Qz5xqeIuzJ1OXRNQU5zfny9vY9TsQ
    zLoWTEvJjniC/yzZk2dRFu7ZC18PTqQgtrBscG4Ie8J3L2mfdVJ0jUQc6wgX7n0/
    Rg6whWJnnAbeP1QqPBvCsT/l2ZDICiegIgpzFLsNi0/4nKAsBPhpw17aFEHMS+fb
    umNeFb8qzNmZRiFGTzYKVJ49QihZER8pFf2/BBSANYYDU7Q6UH3ZSlmFkPTLiHY2
    BE96D0CRHnm7PGehWA7kQoaktQMG4jEvauqMb/E4sI1OTiSIaz2BtiCsvLRqHBsO
    WtoxydDc7pZm2qJtnAEKA+2+9CbziEJkNTpBJhoMOixJu2aa5vsxcnd0ZJvqTTAp
    XWMwl1Z/U7iunzROwdD20uauRLxst4nXd/Pbeo6odf9rkidGwJI1Yfi31xRJkCUy
    wYLFNngyHIJYRJSkvK9TH3xgl+9/98h+5xN61mKSLGJ/Nxk4pmcKinKlijbjlEHP
    /fNdQ6QjRQUQH3fBv5XDGMyjY+KiWwutymdi1s/VvpHDHo8G5FYz5tzTN/Vg4Zh9
    snEMRGEDjs8WQbWXzYr7Evnnb1TKBccqjIKc6FTJxFAx0gbB+9o8MFgUY3sNVmUe
    61iw7nPC5COyxKg8xM8I5T1zFPTi2OF5H+R3h4486EuANBECAwEAAaNTMFEwHQYD
    VR0OBBYEFBBDyMaEySUe9TIQNDPMc/JBQ6hFMB8GA1UdIwQYMBaAFBBDyMaEySUe
    9TIQNDPMc/JBQ6hFMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIB
    AB/MGuIyU2tNAEXtQt0L9APYRuJ60XY2uzZ6/54EeK/sUu3ih5MCm7Exg3RMpleB
    /glFeDI3JeaVqSXvRccttA8HfOzmWlxOmLL7EqjJYstgYGqKilSCGoOm+NlFZWbd
    R5JjUfhDuVIUgGNWFe2fnH66OLHBjRrflm8QuiLnXA6Jv7x3gbFl5qMd3RhpzsbB
    0j872MawvjgrzoK4ro7loAygX02RWC6a8/cg38bRD0i0BaWeqw5lIi5bu8pI2mnw
    kGL3o8e0e3K7epUjAOsHui5U/cTuK5z9dBlJvTET57rwUGoMNdYog93YctlzHo8W
    PzYlOi+P7923zgu3UjOuWCP4P6Y4LBbU0NTdRIKcKOpRePeY4cFVtboJYLQpeZIL
    jIW5ml+KOVabbxhnXR/YLFY4XMjt5Vx4QfKDGDvlo/hJjCgZaTIDBb7DE967Ys/0
    mNpgcRMeta85Ysw8ITcsQvU4/ZWkSYYaEkZjsIb50r7EWiwowZQyZMTjlg3TstVE
    47mTq9koUuImkettXsdoJkuPBaBIvEJSp7zZvG9vPc3EyIWZRS/g85rRujIhGlIe
    80g/4RG/g5xKV5rxRn6bLaDSjfmKBFvbQWGOjfWuscAscMaw/nBqzS1AHzFL1HJW
    LgctAJNNNpRnCBXHQGpAMOAf9kG0ehu5sVj59kOvyzUx
    -----END CERTIFICATE-----
